### Problem definition  
The objective is to use the data to build the model that can predict the Energy Star Score and to interpret the results to find which factor influence the most  
The model we will use:
- Supervised: as we can access both features and target
- Regression: as the Enery Star Score is the continuous type

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
sns.set(font_scale = 2)

#No WARNING ABOUT SETTING VALUE ON COPY OF SLICE
pd.options.mode.chained_assignment = None

#DISPLAY UP TO 60 COLUMNS IN THE DATAFRAME
pd.set_option('display.max_columns',60)

#SET DEFAULT FONT SIZE
plt.rcParams['font.size'] = 24

#INTERNAL IPYTHON TOOLS FOR SETTING FIGURE SIZE
from IPython.core.pylabtools import figsize

#IMPORT TRAIN_TEST_SPLIT
from sklearn.model_selection import train_test_split

In [2]:
file = r'C:\Users\Nick Pham\Desktop\projects\Github - Master\Data-Science\Walk Though Machine Learning\Data\nyc_benchmarking_disclosure_2017_consumption_data.xlsx'
df = pd.read_excel(file, sheet_name = 'Information and Metrics')
print ('dataframe has been loaded')

dataframe has been loaded

In [3]:
df.head()

,Order,Property Id,Property Name,Parent Property Id,Parent Property Name,BBL - 10 digits,"NYC Borough, Block and Lot (BBL) self-reported",NYC Building Identification Number (BIN),Address 1 (self-reported),Address 2 (self-reported),Postal Code,Street Number,Street Name,Borough,DOF Gross Floor Area (ft²),Self-Reported Gross Floor Area (ft²),Primary Property Type - Self Selected,List of All Property Use Types at Property,Largest Property Use Type,Largest Property Use Type - Gross Floor Area (ft²),2nd Largest Property Use Type,2nd Largest Property Use - Gross Floor Area (ft²),3rd Largest Property Use Type,3rd Largest Property Use Type - Gross Floor Area (ft²),Year Built,Number of Buildings,Occupancy,Metered Areas (Energy),Metered Areas (Water),ENERGY STAR Score,Source EUI (kBtu/ft²),Weather Normalized Source EUI (kBtu/ft²),Site EUI (kBtu/ft²),Weather Normalized Site EUI (kBtu/ft²),Weather Normalized Site Electricity Intensity (kWh/ft²),Weather Normalized Site Natural Gas Intensity (therms/ft²),Fuel Oil #1 Use (kBtu),Fuel Oil #2 Use (kBtu),Fuel Oil #4 Use (kBtu),Fuel Oil #5 & 6 Use (kBtu),Diesel #2 Use (kBtu),Propane Use (kBtu),District Steam Use (kBtu),District Hot Water Use (kBtu),District Chilled Water Use (kBtu),Natural Gas Use (kBtu),Weather Normalized Site Natural Gas Use (therms),Electricity Use - Grid Purchase (kBtu),Electricity Use - Grid Purchase (kWh),Weather Normalized Site Electricity (kWh),Annual Maximum Demand (kW),Annual Maximum Demand (MM/YYYY),Total GHG Emissions (Metric Tons CO2e),Direct GHG Emissions (Metric Tons CO2e),Indirect GHG Emissions (Metric Tons CO2e),Water Use (All Water Sources) (kgal),Water Use Intensity (All Water Sources) (gal/ft²),Water Required?,Generation Date,DOF Benchmarking Submission Status
0,1,4593574,The Argonaut Building,NaN,NaN,1.010288e+09,1010287502,1024898,224 West 57th St,NaN,10019,Not found,Not found,Manhattan,Not found,169416,Office,"Bank Branch, Office",Office,164754.0,Bank Branch,4662.0,NaN,NaN,1909,1,95,Whole Building,Whole Building,90.0,138.4,141.0,53.8,56.2,11.3,0.1,NaN,NaN,NaN,NaN,NaN,NaN,1133475.1,NaN,NaN,1435754.7,16672.2,6551394.1,1920103.6,1920103.6,NaN,NaT,732.4,76.3,656.1,3635.5,21.46,Not found,2018-02-14,Not found
1,3,2967701,Cathedral Preparatory Seminary,NaN,NaN,4.018720e+09,4-01872-0007,4046340,56-25 92nd Street,NaN,11373,Not found,Not found,Queens,Not found,94380,K-12 School,K-12 School,K-12 School,94380.0,NaN,NaN,NaN,NaN,1963,1,100,Whole Building,NaN,100.0,43.5,46.8,28.4,31.3,2.0,0.2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2068300.1,23243.7,616343.7,180640.0,184131.9,NaN,NaT,164.5,109.9,54.6,102.9,1.09,Not found,2018-02-14,Not found
2,4,4898531,The Nomad Hotel,NaN,NaN,1.008290e+09,1-00829-0050,1080710,1170 Broadway,NaN,10001-7507,Not found,Not found,Manhattan,Not found,125000,Hotel,Hotel,Hotel,125000.0,NaN,NaN,NaN,NaN,1999,1,85,Whole Building,Whole Building,83.0,271.1,274.7,130.2,133.7,18.8,0.7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8245445.1,86776.9,8033914.4,2354605.3,2354605.3,NaN,NaT,1150.2,438.0,712.3,10762.6,86.10,Not found,2018-02-14,Not found
3,5,2917939,10 West 27 Street Corp,NaN,NaN,1.008280e+09,1-00828-0053,1015657,1155 Broadway,NaN,10001,Not found,Not found,Manhattan,Not found,50000,Hotel,Hotel,Hotel,50000.0,NaN,NaN,NaN,NaN,1994,1,100,Whole Building,NaN,27.0,163.0,167.9,76.5,80.8,11.7,0.4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1848519.4,20520.9,1976691.9,579335.2,582516.1,NaN,NaT,273.4,98.2,175.3,790.1,15.80,Not found,2018-02-14,Not found
4,6,3878205,Westbury Realty,NaN,NaN,1.000650e+09,1-00065-0024,1001105,24 John Street,NaN,10038,Not found,Not found,Manhattan,Not found,50000,Hotel,Hotel,Hotel,50000.0,NaN,NaN,NaN,NaN,2012,1,0,Whole Building,Whole Building,99.0,64.2,64.2,20.5,20.5,6.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1022951.6,299809.9,299809.9,NaN,NaT,90.7,0.0,90.7,143.0,2.86,Not found,2018-02-14,Not found

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 34355 entries, 0 to 34354
Data columns (total 60 columns):
 #   Column                                                      Non-Null Count  Dtype
---  ------                                                      --------------  -----
 0   Order                                                       34355 non-null  int64
 1   Property Id                                                 34355 non-null  int64
 2   Property Name                                               34355 non-null  object
 3   Parent Property Id                                          1723 non-null   object
 4   Parent Property Name                                        1723 non-null   object
 5   BBL - 10 digits                                             33625 non-null  float64
 6   NYC Borough, Block and Lot (BBL) self-reported              33626 non-null  object
 7   NYC Building Identification Number (BIN)                    33123 non-null  object
 8   Address 1 (self-reported)                                   34355 non-null  object
 9   Address 2 (self-reported)                                   427 non-null    object
 10  Postal Code                                                 34355 non-null  object
 11  Street Number                                               34355 non-null  object
 12  Street Name                                                 34355 non-null  object
 13  Borough                                                     34355 non-null  object
 14  DOF Gross Floor Area (ft²)                                  34355 non-null  object
 15  Self-Reported Gross Floor Area (ft²)                        34355 non-null  int64
 16  Primary Property Type - Self Selected                       34355 non-null  object
 17  List of All Property Use Types at Property                  34342 non-null  object
 18  Largest Property Use Type                                   34323 non-null  object
 19  Largest Property Use Type - Gross Floor Area (ft²)          34323 non-null  float64
 20  2nd Largest Property Use Type                               7226 non-null   object
 21  2nd Largest Property Use - Gross Floor Area (ft²)           7226 non-null   float64
 22  3rd Largest Property Use Type                               2450 non-null   object
 23  3rd Largest Property Use Type - Gross Floor Area (ft²)      2450 non-null   float64
 24  Year Built                                                  34355 non-null  int64
 25  Number of Buildings                                         34355 non-null  int64
 26  Occupancy                                                   34355 non-null  int64
 27  Metered Areas (Energy)                                      31710 non-null  object
 28  Metered Areas  (Water)                                      14546 non-null  object
 29  ENERGY STAR Score                                           25454 non-null  float64
 30  Source EUI (kBtu/ft²)                                       31888 non-null  float64
 31  Weather Normalized Source EUI (kBtu/ft²)                    28560 non-null  float64
 32  Site EUI (kBtu/ft²)                                         31888 non-null  float64
 33  Weather Normalized Site EUI (kBtu/ft²)                      28560 non-null  float64
 34  Weather Normalized Site Electricity Intensity (kWh/ft²)     31001 non-null  float64
 35  Weather Normalized Site Natural Gas Intensity (therms/ft²)  28042 non-null  float64
 36  Fuel Oil #1 Use (kBtu)                                      36 non-null     float64
 37  Fuel Oil #2 Use (kBtu)                                      5664 non-null   float64
 38  Fuel Oil #4 Use (kBtu)                                      2378 non-null   float64
 39  Fuel Oil #5 & 6 Use (kBtu)                                  484 non-null    float64
 40  Diesel #2 Use (kBtu)                                        70 non-null     float64
 41  Propane Use (kBtu)                                          1 non-null      float64
 42  District Steam Use (kBtu)                                   1568 non-null   float64
 43  District Hot Water Use (kBtu)                               8 non-null      float64
 44  District Chilled Water Use (kBtu)                           30 non-null     float64
 45  Natural Gas Use (kBtu)                                      28819 non-null  float64
 46  Weather Normalized Site Natural Gas Use (therms)            28047 non-null  float64
 47  Electricity Use - Grid Purchase (kBtu)                      31576 non-null  float64
 48  Electricity Use - Grid Purchase (kWh)                       31576 non-null  float64
 49  Weather Normalized Site Electricity (kWh)                   31013 non-null  float64
 50  Annual Maximum Demand (kW)                                  2383 non-null   float64
 51  Annual Maximum Demand (MM/YYYY)                             2383 non-null   datetime64[ns]
 52  Total GHG Emissions (Metric Tons CO2e)                      32957 non-null  float64
 53  Direct GHG Emissions (Metric Tons CO2e)                     33116 non-null  float64
 54  Indirect GHG Emissions (Metric Tons CO2e)                   33088 non-null  float64
 55  Water Use (All Water Sources) (kgal)                        18280 non-null  float64
 56  Water Use Intensity (All Water Sources) (gal/ft²)           18271 non-null  float64
 57  Water Required?                                             34355 non-null  object
 58  Generation Date                                             34355 non-null  datetime64[ns]
 59  DOF Benchmarking Submission Status                          34355 non-null  object
dtypes: datetime64[ns](2), float64(31), int64(6), object(21)
memory usage: 15.7+ MB

---

## Missing values

### Create a table as a summary

In [5]:
miss_df = pd.DataFrame()

miss_values = df.isnull().sum()

miss_df['Number of Miss_Values'] = miss_values
miss_df['Percentage'] = 100*miss_values / len(df) 

#Sort the table into descending order to have an intuitive view
miss_df = miss_df.sort_values('Percentage', ascending = False).round(1)
miss_df

,Number of Miss_Values,Percentage
Propane Use (kBtu),34354,100.0
District Hot Water Use (kBtu),34347,100.0
District Chilled Water Use (kBtu),34325,99.9
Fuel Oil #1 Use (kBtu),34319,99.9
Diesel #2 Use (kBtu),34285,99.8
Address 2 (self-reported),33928,98.8
Fuel Oil #5 & 6 Use (kBtu),33871,98.6
District Steam Use (kBtu),32787,95.4
Parent Property Id,32632,95.0
Parent Property Name,32632,95.0
Fuel Oil #4 Use (kBtu),31977,93.1
Annual Maximum Demand (MM/YYYY),31972,93.1
Annual Maximum Demand (kW),31972,93.1
3rd Largest Property Use Type - Gross Floor Area (ft²),31905,92.9
3rd Largest Property Use Type,31905,92.9
Fuel Oil #2 Use (kBtu),28691,83.5
2nd Largest Property Use Type,27129,79.0
2nd Largest Property Use - Gross Floor Area (ft²),27129,79.0
Metered Areas (Water),19809,57.7
Water Use Intensity (All Water Sources) (gal/ft²),16084,46.8
Water Use (All Water Sources) (kgal),16075,46.8
ENERGY STAR Score,8901,25.9
Weather Normalized Site Natural Gas Intensity (therms/ft²),6313,18.4
Weather Normalized Site Natural Gas Use (therms),6308,18.4
Weather Normalized Site EUI (kBtu/ft²),5795,16.9
Weather Normalized Source EUI (kBtu/ft²),5795,16.9
Natural Gas Use (kBtu),5536,16.1
Weather Normalized Site Electricity Intensity (kWh/ft²),3354,9.8
Weather Normalized Site Electricity (kWh),3342,9.7
Electricity Use - Grid Purchase (kWh),2779,8.1
Electricity Use - Grid Purchase (kBtu),2779,8.1
Metered Areas (Energy),2645,7.7
Source EUI (kBtu/ft²),2467,7.2
Site EUI (kBtu/ft²),2467,7.2
Total GHG Emissions (Metric Tons CO2e),1398,4.1
Indirect GHG Emissions (Metric Tons CO2e),1267,3.7
Direct GHG Emissions (Metric Tons CO2e),1239,3.6
NYC Building Identification Number (BIN),1232,3.6
BBL - 10 digits,730,2.1
"NYC Borough, Block and Lot (BBL) self-reported",729,2.1
Largest Property Use Type - Gross Floor Area (ft²),32,0.1
Largest Property Use Type,32,0.1
List of All Property Use Types at Property,13,0.0
Water Required?,0,0.0
Generation Date,0,0.0
Order,0,0.0
Property Id,0,0.0
Occupancy,0,0.0
Number of Buildings,0,0.0
Year Built,0,0.0
Primary Property Type - Self Selected,0,0.0
Self-Reported Gross Floor Area (ft²),0,0.0
DOF Gross Floor Area (ft²),0,0.0
Borough,0,0.0
Street Name,0,0.0
Street Number,0,0.0
Postal Code,0,0.0
Address 1 (self-reported),0,0.0
Property Name,0,0.0
DOF Benchmarking Submission Status,0,0.0

In [6]:
# Drop the columns which contain more than 70% of missing values
rows = miss_df[miss_df['Percentage']>70]
print(list(rows.index))
print(len(list(rows.index)))

['Propane Use (kBtu)', 'District Hot Water Use (kBtu)', 'District Chilled Water Use (kBtu)', 'Fuel Oil #1 Use (kBtu)', 'Diesel #2 Use (kBtu)', 'Address 2 (self-reported)', 'Fuel Oil #5 & 6 Use (kBtu)', 'District Steam Use (kBtu)', 'Parent Property Id', 'Parent Property Name', 'Fuel Oil #4 Use (kBtu)', 'Annual Maximum Demand (MM/YYYY)', 'Annual Maximum Demand (kW)', '3rd Largest Property Use Type - Gross Floor Area (ft²)', '3rd Largest Property Use Type', 'Fuel Oil #2 Use (kBtu)', '2nd Largest Property Use Type', '2nd Largest Property Use - Gross Floor Area (ft²)']
18

In [12]:
data = df.drop(columns = list(rows.index))
data.head()

,Order,Property Id,Property Name,BBL - 10 digits,"NYC Borough, Block and Lot (BBL) self-reported",NYC Building Identification Number (BIN),Address 1 (self-reported),Postal Code,Street Number,Street Name,Borough,DOF Gross Floor Area (ft²),Self-Reported Gross Floor Area (ft²),Primary Property Type - Self Selected,List of All Property Use Types at Property,Largest Property Use Type,Largest Property Use Type - Gross Floor Area (ft²),Year Built,Number of Buildings,Occupancy,Metered Areas (Energy),Metered Areas (Water),score,Source EUI (kBtu/ft²),Weather Normalized Source EUI (kBtu/ft²),Site EUI (kBtu/ft²),Weather Normalized Site EUI (kBtu/ft²),Weather Normalized Site Electricity Intensity (kWh/ft²),Weather Normalized Site Natural Gas Intensity (therms/ft²),Natural Gas Use (kBtu),Weather Normalized Site Natural Gas Use (therms),Electricity Use - Grid Purchase (kBtu),Electricity Use - Grid Purchase (kWh),Weather Normalized Site Electricity (kWh),Total GHG Emissions (Metric Tons CO2e),Direct GHG Emissions (Metric Tons CO2e),Indirect GHG Emissions (Metric Tons CO2e),Water Use (All Water Sources) (kgal),Water Use Intensity (All Water Sources) (gal/ft²),Water Required?,Generation Date,DOF Benchmarking Submission Status
0,1,4593574,The Argonaut Building,1.010288e+09,1010287502,1024898,224 West 57th St,10019,Not found,Not found,Manhattan,Not found,169416,Office,"Bank Branch, Office",Office,164754.0,1909,1,95,Whole Building,Whole Building,90.0,138.4,141.0,53.8,56.2,11.3,0.1,1435754.7,16672.2,6551394.1,1920103.6,1920103.6,732.4,76.3,656.1,3635.5,21.46,Not found,2018-02-14,Not found
1,3,2967701,Cathedral Preparatory Seminary,4.018720e+09,4-01872-0007,4046340,56-25 92nd Street,11373,Not found,Not found,Queens,Not found,94380,K-12 School,K-12 School,K-12 School,94380.0,1963,1,100,Whole Building,NaN,100.0,43.5,46.8,28.4,31.3,2.0,0.2,2068300.1,23243.7,616343.7,180640.0,184131.9,164.5,109.9,54.6,102.9,1.09,Not found,2018-02-14,Not found
2,4,4898531,The Nomad Hotel,1.008290e+09,1-00829-0050,1080710,1170 Broadway,10001-7507,Not found,Not found,Manhattan,Not found,125000,Hotel,Hotel,Hotel,125000.0,1999,1,85,Whole Building,Whole Building,83.0,271.1,274.7,130.2,133.7,18.8,0.7,8245445.1,86776.9,8033914.4,2354605.3,2354605.3,1150.2,438.0,712.3,10762.6,86.10,Not found,2018-02-14,Not found
3,5,2917939,10 West 27 Street Corp,1.008280e+09,1-00828-0053,1015657,1155 Broadway,10001,Not found,Not found,Manhattan,Not found,50000,Hotel,Hotel,Hotel,50000.0,1994,1,100,Whole Building,NaN,27.0,163.0,167.9,76.5,80.8,11.7,0.4,1848519.4,20520.9,1976691.9,579335.2,582516.1,273.4,98.2,175.3,790.1,15.80,Not found,2018-02-14,Not found
4,6,3878205,Westbury Realty,1.000650e+09,1-00065-0024,1001105,24 John Street,10038,Not found,Not found,Manhattan,Not found,50000,Hotel,Hotel,Hotel,50000.0,2012,1,0,Whole Building,Whole Building,99.0,64.2,64.2,20.5,20.5,6.0,NaN,NaN,NaN,1022951.6,299809.9,299809.9,90.7,0.0,90.7,143.0,2.86,Not found,2018-02-14,Not found

---

## Exploratory Data Analysis (EDA)
Theory: is the process where we plots and calculate statistic in order to explore the data. The purpose is to find anomalities, patterns, trends, or relationships (for examples, find correlation between 2 variables) or they can be used to decide which variables will be used
> We will start with Energy Star Score as this is our target , we will also change the name in "score" for easier applied

In [13]:
data = data.rename(columns = {'ENERGY STAR Score':'score'})
data.head()

,Order,Property Id,Property Name,BBL - 10 digits,"NYC Borough, Block and Lot (BBL) self-reported",NYC Building Identification Number (BIN),Address 1 (self-reported),Postal Code,Street Number,Street Name,Borough,DOF Gross Floor Area (ft²),Self-Reported Gross Floor Area (ft²),Primary Property Type - Self Selected,List of All Property Use Types at Property,Largest Property Use Type,Largest Property Use Type - Gross Floor Area (ft²),Year Built,Number of Buildings,Occupancy,Metered Areas (Energy),Metered Areas (Water),score,Source EUI (kBtu/ft²),Weather Normalized Source EUI (kBtu/ft²),Site EUI (kBtu/ft²),Weather Normalized Site EUI (kBtu/ft²),Weather Normalized Site Electricity Intensity (kWh/ft²),Weather Normalized Site Natural Gas Intensity (therms/ft²),Natural Gas Use (kBtu),Weather Normalized Site Natural Gas Use (therms),Electricity Use - Grid Purchase (kBtu),Electricity Use - Grid Purchase (kWh),Weather Normalized Site Electricity (kWh),Total GHG Emissions (Metric Tons CO2e),Direct GHG Emissions (Metric Tons CO2e),Indirect GHG Emissions (Metric Tons CO2e),Water Use (All Water Sources) (kgal),Water Use Intensity (All Water Sources) (gal/ft²),Water Required?,Generation Date,DOF Benchmarking Submission Status
0,1,4593574,The Argonaut Building,1.010288e+09,1010287502,1024898,224 West 57th St,10019,Not found,Not found,Manhattan,Not found,169416,Office,"Bank Branch, Office",Office,164754.0,1909,1,95,Whole Building,Whole Building,90.0,138.4,141.0,53.8,56.2,11.3,0.1,1435754.7,16672.2,6551394.1,1920103.6,1920103.6,732.4,76.3,656.1,3635.5,21.46,Not found,2018-02-14,Not found
1,3,2967701,Cathedral Preparatory Seminary,4.018720e+09,4-01872-0007,4046340,56-25 92nd Street,11373,Not found,Not found,Queens,Not found,94380,K-12 School,K-12 School,K-12 School,94380.0,1963,1,100,Whole Building,NaN,100.0,43.5,46.8,28.4,31.3,2.0,0.2,2068300.1,23243.7,616343.7,180640.0,184131.9,164.5,109.9,54.6,102.9,1.09,Not found,2018-02-14,Not found
2,4,4898531,The Nomad Hotel,1.008290e+09,1-00829-0050,1080710,1170 Broadway,10001-7507,Not found,Not found,Manhattan,Not found,125000,Hotel,Hotel,Hotel,125000.0,1999,1,85,Whole Building,Whole Building,83.0,271.1,274.7,130.2,133.7,18.8,0.7,8245445.1,86776.9,8033914.4,2354605.3,2354605.3,1150.2,438.0,712.3,10762.6,86.10,Not found,2018-02-14,Not found
3,5,2917939,10 West 27 Street Corp,1.008280e+09,1-00828-0053,1015657,1155 Broadway,10001,Not found,Not found,Manhattan,Not found,50000,Hotel,Hotel,Hotel,50000.0,1994,1,100,Whole Building,NaN,27.0,163.0,167.9,76.5,80.8,11.7,0.4,1848519.4,20520.9,1976691.9,579335.2,582516.1,273.4,98.2,175.3,790.1,15.80,Not found,2018-02-14,Not found
4,6,3878205,Westbury Realty,1.000650e+09,1-00065-0024,1001105,24 John Street,10038,Not found,Not found,Manhattan,Not found,50000,Hotel,Hotel,Hotel,50000.0,2012,1,0,Whole Building,Whole Building,99.0,64.2,64.2,20.5,20.5,6.0,NaN,NaN,NaN,1022951.6,299809.9,299809.9,90.7,0.0,90.7,143.0,2.86,Not found,2018-02-14,Not found